### ISSUE TITLE
Question about CMSIS/Target_ATMEL files

### ISSUE THREAD

**Issue by spiderkeys** [synthetos/Motate#4]
Somewhat unrelated to Motate, but I'm curious where you found this curated set of ATMEL header files? I am trying to find out who keeps these things up to date and where I can grab the latest official releases. Have yet to find them on the ATMEL website. Effectively they are contained in the ASF release, but they are not nicely organized the way I usually find them in CMSIS/Target folders in various projects. Thanks for any info you can provide.

**Comment by giseburt** [comment]
Hi @spiderkeys,

I indeed pulled these from the ASF and then cleaned them up. Generally, the vendor versions of CMSIS need some cleanup. For example, the ASF version had includes that eventually seemed to pull in half of ASF, and as it stands it pulls in more than I would prefer.

Note the CMSIS files from https://github.com/synthetos/Motate/tree/sam4e-port/MotateProject/motate/cmsis/TARGET_Atmel are the latest, and you're welcome to use them.

I have a hard time finding these as well. Generally you have to install whatever crappy IDE the vendor provides, then extract these files and clean them up. I wish I had a better answer, but that appears to be the state of things ATM.

-Rob

PS: Sorry for the slow reply.
